spring:
  application:
    name: MKAuth

server:
  port: 8881
  servlet:
    context-path: /api
logging:
  level:
    org.springframework.security: DEBUG
security:
  oauth2:
    resource:
      serviceId: ${PREFIX:}resource
      filter-order: 3